### ISSUE TITLE
About deployment

### ISSUE THREAD

**Issue by hanzhi0410** [zeonsunlightyu/LocomotionWithNP3O#1]
Thank you for your work. May I ask if your deployment was done on Jetson？

**Comment by zeonsunlightyu** [comment]
yes，it is deployment on jetson ：）

**Comment by zeonsunlightyu** [comment]
Please checkout nvidia official website, a arm64 version of PyTorch can be found, the so file you need to run libtorch also comes with it :)

**Comment by hanzhi0410** [comment]
Thank you for your reply. I have successfully resolved my issue.

**Comment by ZhangLiang-Cencen** [comment]
> Please checkout nvidia official website, a arm64 version of PyTorch can be found, the so file you need to run libtorch also comes with it :)

Could you please express a website link for a arm64 version of libtorch？I could not find it.
Thank you

**Comment by zeonsunlightyu** [comment]
hi,please checkout the link below～

https://docs.nvidia.com/deeplearning/frameworks/install-pytorch-jetson-platform/index.html

**Comment by ZhangLiang-Cencen** [comment]
Thanks for your reply.

> hi,please checkout the link below～
> 
> https://docs.nvidia.com/deeplearning/frameworks/install-pytorch-jetson-platform/index.html

**Comment by AlessiaLiNoce** [comment]
Hi, great work :) Just one little question: you used the unitree_guide with go2 to control the real robot or only for the gazebo simulation?

**Comment by zeonsunlightyu** [comment]
Hi, Alessia
Thanks for pay attention to my code, I believe that the unitree guide is needed for gazebo and deployment, I will update my repo shortly to remove some redundant dependencies but Unitree guide will remain unchanged

发自我的iPhone


------------------ Original ------------------
From: Alessia Li Noce ***@***.***&gt;
Date: Wed,Jun 26,2024 3:33 PM
To: zeonsunlightyu/LocomotionWithNP3O ***@***.***&gt;
Cc: zeonsunlightyu ***@***.***&gt;, Comment ***@***.***&gt;
Subject: Re: [zeonsunlightyu/LocomotionWithNP3O] About deployment (Issue #1)

**Comment by Aleksej9521** [comment]
Hi, thanks for the answer :) about the deploy with unitree guide, can you tell me the steps from joystick to code to how correctly upload and start the state machine?
